//! Generates the systemd unit and Caddy site block for a project.
//!
//! Both outputs are pure functions of the config and the layout: nothing here
//! touches the filesystem, so the exact text a deploy would install can be
//! reviewed — and tested — before any host exists.

use crate::config::{Project, Role, Service};
use crate::layout::Layout;

/// Wraps a command for `/bin/sh -lc '...'`. systemd requires an absolute
/// ExecStart path, and builders write ecosystem commands like `npm run start`,
/// so the command runs through a login shell. A literal single quote is escaped
/// the POSIX way rather than rejected.
fn shell_quote(command: &str) -> String {
    format!("'{}'", command.replace('\'', r"'\''"))
}

pub fn systemd_unit(project: &Project, service: &Service, role: Role, layout: &Layout) -> String {
    let name = &project.name;
    let user = layout.service_user();
    let workdir = layout.service_dir(role).display().to_string();
    let log = layout.log_file(role).display().to_string();
    let exec = shell_quote(service.start_command());

    let mut unit = String::new();
    unit.push_str(&format!(
        "# Generated by sgbc. Edits are overwritten on the next deploy.\n\
         [Unit]\n\
         Description={name} {role} (Solana Ghana Builder Cloud)\n\
         After=network-online.target\n\
         Wants=network-online.target\n\
         \n\
         [Service]\n\
         Type=simple\n\
         User={user}\n\
         Group={user}\n\
         WorkingDirectory={workdir}\n\
         ExecStart=/bin/sh -lc {exec}\n\
         Restart=on-failure\n\
         RestartSec=5\n\
         \n\
         Environment=NODE_ENV=production\n"
    ));

    if let Some(port) = service.port {
        unit.push_str(&format!("Environment=PORT={port}\n"));
    }

    unit.push_str(&format!(
        "\n\
         StandardOutput=append:{log}\n\
         StandardError=append:{log}\n\
         \n\
         # The host is shared, so a builder's process is confined to its own\n\
         # project directory and is given no route to privilege.\n\
         NoNewPrivileges=true\n\
         PrivateTmp=true\n\
         PrivateDevices=true\n\
         ProtectSystem=strict\n\
         ProtectHome=true\n\
         ProtectKernelTunables=true\n\
         ProtectKernelModules=true\n\
         ProtectControlGroups=true\n\
         RestrictSUIDSGID=true\n\
         RestrictNamespaces=true\n\
         LockPersonality=true\n\
         ReadWritePaths={project_dir} {logs_dir}\n\
         \n\
         # A runaway build or leak must not take the host down with it.\n\
         MemoryMax=512M\n\
         TasksMax=256\n\
         \n\
         [Install]\n\
         WantedBy=multi-user.target\n",
        log = log,
        project_dir = layout.project_dir().display(),
        logs_dir = layout.logs_dir().display(),
    ));

    unit
}

/// The Caddy fragment for a project: one site block per service that has a
/// domain. Caddy provisions HTTPS for each name on its own.
pub fn caddy_fragment(project: &Project, layout: &Layout) -> String {
    let mut out = format!(
        "# Generated by sgbc for {}. Edits are overwritten on the next deploy.\n",
        project.name
    );

    let mut blocks = 0;
    for (role, service) in project.services() {
        let (Some(domain), Some(port)) = (project.domain_for(role), service.port) else {
            continue;
        };
        blocks += 1;
        out.push_str(&format!(
            "\n{domain} {{\n\
             \tencode zstd gzip\n\
             \treverse_proxy 127.0.0.1:{port}\n\
             \tlog {{\n\
             \t\toutput file {access}\n\
             \t}}\n\
             }}\n",
            access = layout.access_log_file(role).display(),
        ));
    }

    if blocks == 0 {
        out.push_str(
            "\n# No domain is configured for this project, so nothing is routed.\n\
             # Workers, bots and indexers are expected to look like this.\n",
        );
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn quotes_a_plain_command() {
        assert_eq!(shell_quote("npm run start"), "'npm run start'");
    }

    #[test]
    fn escapes_a_single_quote_so_the_unit_stays_well_formed() {
        // Without escaping, the closing quote would land early and the rest of
        // the command would be reinterpreted by the shell.
        assert_eq!(shell_quote("echo 'hi'"), r"'echo '\''hi'\'''");
    }

    /// The quoting is only correct if a real shell reproduces the original
    /// string exactly, so the round trip is checked against /bin/sh itself.
    #[test]
    fn a_real_shell_reproduces_the_original_command() {
        for original in [
            "npm run start",
            "echo 'hi'",
            "a'b'c",
            "sh -c 'nested \"quotes\"'",
            "printf %s$HOME",
            "echo `id`",
        ] {
            let output = std::process::Command::new("/bin/sh")
                .arg("-c")
                .arg(format!("printf %s {}", shell_quote(original)))
                .output()
                .expect("could not run /bin/sh");
            assert_eq!(
                String::from_utf8_lossy(&output.stdout),
                original,
                "round trip failed for {original:?}"
            );
        }
    }
}
